site_name: solidbox
repo_url: https://github.com/aliev/solidbox
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
nav:
  - Home: index.md
  - Unit Of work: sections/uow.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
